version: "3"
services:
  artexhibit-app:
    build: .
    depends_on:
      - "artexhibit-db"
    links:
      - artexhibit-db
    ports:
      - "8080:8080"
  artexhibit-db:
    image: mysql:latest
    container_name: artexhibit-db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=artexhibit_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
      - TZ=Europe/Rome
